### ISSUE TITLE
Error in starting

### ISSUE THREAD

**Issue by pcav** [gilliM/PLCS#2]
Clicking on Auto returns an error:

Errore durante l'esecuzione di codice Python:

Traceback (most recent call last):
  File "/home/paolo/Scrivania/butta/config/python/plugins/PLCS/widgets/mainDock.py", line 339, in on_auto_pushButton_released
    for index, graphic in enumerate(self.ui.graphicList):
AttributeError: 'Ui_DockWidget' object has no attribute 'graphicList'

**Comment by gilliM** [comment]
Is the error reproductible ?

On Tue, Mar 24, 2015 at 6:42 PM, Paolo Cavallini notifications@github.com
wrote:

> Clicking on Auto returns an error:
> 
> Errore durante l'esecuzione di codice Python:
> 
> Traceback (most recent call last):
> File
> "/home/paolo/Scrivania/butta/config/python/plugins/PLCS/widgets/mainDock.py",
> line 339, in on_auto_pushButton_released
> for index, graphic in enumerate(self.ui.graphicList):
> AttributeError: 'Ui_DockWidget' object has no attribute 'graphicList'
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gilliM/PLCS/issues/2.

## 

_camp__to__camp_
INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

_Gillian Milani_

Ingénieur en environnement
Stagiaire

+41 21 619 10 10 (central)
+41 21 619 10 48 (direct)
_Camptocamp SA_
Quartier de l'Innovation EPFL, PSE-A
1015 Lausanne
Suisse

**Comment by pcav** [comment]
Yes: just load a raster and press "Auto", that's it.
Thanks.

**Comment by pcav** [comment]
Clicking on Save returns:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/PLCS/widgets/mainDock.py", line 270, in transform
    bandNum1 = self.currentCBIndex(0) + 1
  File "/home/paolo/.qgis2/python/plugins/PLCS/widgets/mainDock.py", line 131, in currentCBIndex
    return self.ui.bandComboboxList[index].itemData(
AttributeError: 'Ui_DockWidget' object has no attribute 'bandComboboxList'

**Comment by gilliM** [comment]
Ok, i've found the problem. I told you when it's solved.

Until this time, if you want to test it, just reselected the raster in the combobox once it's loaded.

**Comment by pcav** [comment]
Confirmed, now it works with your trick.

**Comment by pcav** [comment]
However, moving a point results in:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/PLCS/uis/ui_mainDock.py", line 292, in mouseReleaseEvent
    self.resetHistograms()
  File "/home/paolo/.qgis2/python/plugins/PLCS/uis/ui_mainDock.py", line 307, in resetHistograms
    self.redrawNewHistogram()
  File "/home/paolo/.qgis2/python/plugins/PLCS/uis/ui_mainDock.py", line 331, in redrawNewHistogram
    newData = self.transformData(self.data)
  File "/home/paolo/.qgis2/python/plugins/PLCS/uis/ui_mainDock.py", line 350, in transformData
    while (dat > X[i]):
IndexError: list index out of range

**Comment by gilliM** [comment]
I've changed the signal for for the combobox, it react now when a raster is loaded or deleted from the qgis layer tree, but there is no more error.

About the second problem (moving point), you're using a DEM ? if yes, i need to prevent it (It's sensless to change altitude value)

**Comment by pcav** [comment]
Thanks.
Yes, using a DEM.

**Comment by gilliM** [comment]
Thanks for the testing :+1:

**Comment by pcav** [comment]
My pleasure, one of the ways I'm contributing back to the project :)

**Comment by gilliM** [comment]
Do you have 8-bits imagery raster data ?

On Wed, Mar 25, 2015 at 10:53 AM, Paolo Cavallini notifications@github.com
wrote:

> My pleasure, one of the ways I'm contributing back to the project :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gilliM/PLCS/issues/2#issuecomment-85964638.

## 

_camp__to__camp_
INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

_Gillian Milani_

Ingénieur en environnement
Stagiaire

+41 21 619 10 10 (central)
+41 21 619 10 48 (direct)
_Camptocamp SA_
Quartier de l'Innovation EPFL, PSE-A
1015 Lausanne
Suisse

**Comment by pcav** [comment]
Not here at hand, I think.

**Comment by gilliM** [comment]
Here is a landsat image, if you want to try with it. But it should work with any standard image or raster (like Landsat for example)
![le71970282003151asn00](https://cloud.githubusercontent.com/assets/6716422/6824621/21ed3d42-d2f4-11e4-90b8-524cd2053e0f.jpg)

**Comment by pcav** [comment]
I think GH shows just a jpeg preview, not the full image. Perhaps better is you send me a link where I can download the raw image.
Thanks.

**Comment by gilliM** [comment]
You can take it, it's the full image (4.5 MB)

**Comment by gilliM** [comment]
I've uploaded a new version, it should normally fix all bugs cited in this issue ticket. Please confirm it for closing the issue.

**Comment by pcav** [comment]
Fine, thanks!

**Comment by gilliM** [comment]
I thank you, a lot !

On Wed, Mar 25, 2015 at 4:23 PM, Paolo Cavallini notifications@github.com
wrote:

> Fine, thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gilliM/PLCS/issues/2#issuecomment-86080953.

## 

_camp__to__camp_
INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

_Gillian Milani_

Ingénieur en environnement
Stagiaire

+41 21 619 10 10 (central)
+41 21 619 10 48 (direct)
_Camptocamp SA_
Quartier de l'Innovation EPFL, PSE-A
1015 Lausanne
Suisse
