### ISSUE TITLE
module not loaded

### ISSUE THREAD

**Issue by tigarace** [gilliM/PLCS#5]
Hi there, I have just tried to install the PLCS plugin but have the error:

The plugin is broken, No module named lxml

I would like to use the module for histogram equalisation if possible - do you have any advice how to get past this issue?

**Comment by gilliM** [comment]
You work on which platform ?

**Comment by gilliM** [comment]
Sorry, i cannot help you if you don't give basic information. Maybe you just have to pip install it.
